name: globe_flutter_android
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  line_icons: ^2.0.1
  flutter_cube: ^0.1.1

  cupertino_icons: ^1.0.2
  svg_path_parser: ^1.1.1
  provider: ^6.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/top.png
    - assets/cloud.png
    - assets/top.svg
    - assets/data/alternate_names.json
    - assets/data/country_data.json
    - assets/data/country_outlines.json
    - assets/data/social_svgs.json
    - assets/data/symbol_svgs.json
    - assets/data/territories.json


  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 700
